# Generated by Django 6.0.3 on 2026-04-03 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone_and_more'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
    ]
