# Generated by Django 6.0.4 on 2026-04-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
