# Generated by Django 6.0.4 on 2026-04-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_picture'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
    ]
