# Generated by Django 6.0.3 on 2026-03-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipment', models.CharField(max_length=50)),
                ('modelo_equipment', models.CharField(max_length=255)),
                ('quantidade_equipment', models.IntegerField(null=True)),
                ('aluguel', models.FloatField(null=True)),
            ],
        ),
    ]
