# Generated by Django 6.0.5 on 2026-05-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
