# Generated by Django 6.0.5 on 2026-05-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='documento',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
